# Generated by Django 4.2.11 on 2024-11-22 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='available_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewer',
            name='available_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
